/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ExtensaoRouteImport } from './routes/extensao'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiAdminSplatRouteImport } from './routes/api/admin/$'
import { Route as ApiLicenseActionRouteImport } from './routes/api/license/$action'
import { Route as ApiServicesActionRouteImport } from './routes/api/services/$action'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensaoRoute = ExtensaoRouteImport.update({
  id: '/extensao',
  path: '/extensao',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSplatRoute = ApiAdminSplatRouteImport.update({
  id: '/api/admin/$',
  path: '/api/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLicenseActionRoute = ApiLicenseActionRouteImport.update({
  id: '/api/license/$action',
  path: '/api/license/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServicesActionRoute = ApiServicesActionRouteImport.update({
  id: '/api/services/$action',
  path: '/api/services/$action',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRoute
  '/extensao': typeof ExtensaoRoute
  '/loja': typeof LojaRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
  '/api/license/$action': typeof ApiLicenseActionRoute
  '/api/services/$action': typeof ApiServicesActionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRoute
  '/extensao': typeof ExtensaoRoute
  '/loja': typeof LojaRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
  '/api/license/$action': typeof ApiLicenseActionRoute
  '/api/services/$action': typeof ApiServicesActionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRoute
  '/extensao': typeof ExtensaoRoute
  '/loja': typeof LojaRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
  '/api/license/$action': typeof ApiLicenseActionRoute
  '/api/services/$action': typeof ApiServicesActionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/extensao'
    | '/loja'
    | '/auth/callback'
    | '/api/admin/$'
    | '/api/license/$action'
    | '/api/services/$action'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/extensao'
    | '/loja'
    | '/auth/callback'
    | '/api/admin/$'
    | '/api/license/$action'
    | '/api/services/$action'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/extensao'
    | '/loja'
    | '/auth/callback'
    | '/api/admin/$'
    | '/api/license/$action'
    | '/api/services/$action'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRoute
  ExtensaoRoute: typeof ExtensaoRoute
  LojaRoute: typeof LojaRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiAdminSplatRoute: typeof ApiAdminSplatRoute
  ApiLicenseActionRoute: typeof ApiLicenseActionRoute
  ApiServicesActionRoute: typeof ApiServicesActionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensao': {
      id: '/extensao'
      path: '/extensao'
      fullPath: '/extensao'
      preLoaderRoute: typeof ExtensaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/$': {
      id: '/api/admin/$'
      path: '/api/admin/$'
      fullPath: '/api/admin/$'
      preLoaderRoute: typeof ApiAdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/license/$action': {
      id: '/api/license/$action'
      path: '/api/license/$action'
      fullPath: '/api/license/$action'
      preLoaderRoute: typeof ApiLicenseActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/services/$action': {
      id: '/api/services/$action'
      path: '/api/services/$action'
      fullPath: '/api/services/$action'
      preLoaderRoute: typeof ApiServicesActionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRoute,
  ExtensaoRoute: ExtensaoRoute,
  LojaRoute: LojaRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiAdminSplatRoute: ApiAdminSplatRoute,
  ApiLicenseActionRoute: ApiLicenseActionRoute,
  ApiServicesActionRoute: ApiServicesActionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
